CREATE TABLE users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id),
        login TEXT NOT NULL,
        password TEXT NOT NULL,
        login_token TEXT,
        status TEXT,
        status_reason TEXT
);