CREATE TABLE finance_operations (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id),
        owner_id INT REFERENCES users(id) ON DELETE CASCADE,
        category_id INT REFERENCES finance_categories(id) ON DELETE SET NULL,
        operation_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
        amount DECIMAL NOT NULL,
        title VARCHAR(64) NOT NULL,
        description TEXT
);